all:
	pdflatex slides.tex && bibtex slides.aux && pdflatex slides.tex && pdflatex slides.tex

clean: 
	rm -fr *.64 main-logo.pdf _minted-* *.nav *.snm *.pdf *.dvi *.mw *.aux *.bbl *.blg *.brf *.out *.synctex.gz *.log main.pdf main.robust.pdf *.idx *.ilg *.ind *.lof *.lot *.lol *.loalgorithm *.glsdefs *.xdy *.toc *.acn *.glo *.ist *.prv _region*  *~ auto imgs/*.tmp.pdf {imgs,plots}/*-eps-converted-to.pdf; 